#include <algorithm>
#include <array>
#include <boost/signals2.hpp>
#include <clocale>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <dlfcn.h>
#include <filesystem>
#include <functional>
#include <initializer_list>
#include <iostream>
#include <libintl.h>
#include <map>
#include <memory>
#include <nanosvg/nanosvg.h>
#include <nanosvg/nanosvgrast.h>
#include <optional>
#include <sstream>
#include <stdexcept>
#include <string>
#include <string_view>
#include <unordered_map>
#include <unordered_set>
#include <variant>
#include <vector>
#include <wx/app.h>
#include <wx/artprov.h>
#include <wx/aui/auibar.h>
#include <wx/aui/framemanager.h>
#include <wx/bitmap.h>
#include <wx/defs.h>
#include <wx/event.h>
#include <wx/file.h>
#include <wx/frame.h>
#include <wx/gdicmn.h>
#include <wx/gtk/toolbar.h>
#include <wx/image.h>
#include <wx/intl.h>
#include <wx/log.h>
#include <wx/menu.h>
#include <wx/menuitem.h>
#include <wx/mstream.h>
#include <wx/panel.h>
#include <wx/sizer.h>
#include <wx/stackwalk.h>
#include <wx/stdpaths.h>
#include <wx/string.h>
#include <wx/tbarbase.h>
#include <wx/textctrl.h>
#include <wx/toolbar.h>
#include <wx/window.h>
#include <wx/wxprec.h>
